background {
  monitor = 
  path = ~/dotfiles/wallpapers/space.png
  blur_passes = 1
  blur_size = 7
}

input-field {
  monitor =
  size = 20%, 5%
  font_family = Noto Sans
  dots_size = 0.08
}

label {
  monitor =
  text = $TIME
  font_size = 100
  position = 0, -80
}
